---
dist: xenial
install:
  - "pip install pytest pylint pycodestyle pydocstyle PIL google_images_download tkinter"
language: python
python:
  - "3.7"
script:
  - pytest test_final.py
  - pylint final.py
  - pycodestyle final.py
  - pydocstyle final.py
notifications:
  email:
    recipients:
      - none@none.com
    on_success: always
    on_failure: always
