---
dist: xenial
install:
  - "pip install pytest pylint pycodestyle pydocstyle google_images_download"
language: python
python:
  - "3.7"
script:
  - pytest test_final.py
  - pylint test_final.py
  - pycodestyle final.py
  - pydocstyle final.py
notifications:
  email:
    recipients:
      - none@none.com
    on_success: always
    on_failure: always
